# Empresa Logística SA de CV
Empresa Estadounidense dedicada al transporte de mercancías por el país.

## Objetivos del proyecto
La empresa de Logística quiere responder 5 preguntas principales de su negocio:
1- ¿Cómo viene funcionando la operación?
2- ¿Qué rutas generan más ingresos?
3- ¿Qué conductores tienen mejor desempeño?
4- ¿Qué camiones generan mayores costos?
5- ¿Qué clientes generan mayores ganancias?

In [382]:
import pandas as pd
import numpy as np

### Carga de datos

In [383]:
# Dimensiones
df_customers = pd.read_csv('Dataset Logistica/customers.csv')
df_drivers = pd.read_csv('Dataset Logistica/drivers.csv')
df_trucks = pd.read_csv('Dataset Logistica/trucks.csv')
df_trailers = pd.read_csv('Dataset Logistica/trailers.csv')
df_routes = pd.read_csv('Dataset Logistica/routes.csv')

# Tabla de hechos
df_loads = pd.read_csv('Dataset Logistica/loads.csv')
df_trips = pd.read_csv('Dataset Logistica/trips.csv')
df_fuel_purchases = pd.read_csv('Dataset Logistica/fuel_purchases.csv')
df_maintenance_records = pd.read_csv(
    'Dataset Logistica/maintenance_records.csv')
df_delivery_events = pd.read_csv('Dataset Logistica/delivery_events.csv')
df_driver_monthly_metrics = pd.read_csv(
    'Dataset Logistica/driver_monthly_metrics.csv')

### Examinación y estudio de datos

In [384]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               200 non-null    object
 1   customer_name             200 non-null    object
 2   customer_type             200 non-null    object
 3   credit_terms_days         200 non-null    int64
 4   primary_freight_type      200 non-null    object
 5   account_status            200 non-null    object
 6   contract_start_date       200 non-null    object
 7   annual_revenue_potential  200 non-null    int64
dtypes: int64(2), object(6)
memory usage: 12.6+ KB

In [385]:
df_customers.head(3)

,customer_id,customer_name,customer_type,credit_terms_days,primary_freight_type,account_status,contract_start_date,annual_revenue_potential
0,CUST00001,Metro Wholesale,Dedicated,60,General,Inactive,2020-02-20,985117
1,CUST00002,National Retail,Contract,30,Retail,Active,2021-06-02,4936566
2,CUST00003,XYZ Industries,Contract,30,Consumer Goods,Active,2020-09-04,3102814

In [386]:
df_drivers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driver_id          150 non-null    object
 1   first_name         150 non-null    object
 2   last_name          150 non-null    object
 3   hire_date          150 non-null    object
 4   termination_date   26 non-null     object
 5   license_number     150 non-null    object
 6   license_state      150 non-null    object
 7   date_of_birth      150 non-null    object
 8   home_terminal      150 non-null    object
 9   employment_status  150 non-null    object
 10  cdl_class          150 non-null    object
 11  years_experience   150 non-null    int64
dtypes: int64(1), object(11)
memory usage: 14.2+ KB

In [387]:
df_drivers.head(3)

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3
1,DRV00002,William,Martin,2020-10-02,NaN,DL128955006,GA,1976-11-03,Columbus,Active,A,20
2,DRV00003,Charles,Hernandez,2021-09-21,NaN,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19

In [388]:
df_trucks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   truck_id               120 non-null    object
 1   unit_number            120 non-null    int64
 2   make                   120 non-null    object
 3   model_year             120 non-null    int64
 4   vin                    120 non-null    object
 5   acquisition_date       120 non-null    object
 6   acquisition_mileage    120 non-null    int64
 7   fuel_type              120 non-null    object
 8   tank_capacity_gallons  120 non-null    int64
 9   status                 120 non-null    object
 10  home_terminal          120 non-null    object
dtypes: int64(4), object(7)
memory usage: 10.4+ KB

In [389]:
df_trucks.head(3)

,truck_id,unit_number,make,model_year,vin,acquisition_date,acquisition_mileage,fuel_type,tank_capacity_gallons,status,home_terminal
0,TRK00001,3463,Peterbilt,2016,1VV205190335317039,2017-04-27,18814,Diesel,200,Active,Omaha
1,TRK00002,6461,Kenworth,2015,1NV753749606229960,2018-10-04,26795,Diesel,150,Active,Seattle
2,TRK00003,2335,Peterbilt,2018,1NT803101860493229,2020-09-17,11795,Diesel,150,Maintenance,Atlanta

In [390]:
df_trailers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   trailer_id        180 non-null    object
 1   trailer_number    180 non-null    int64
 2   trailer_type      180 non-null    object
 3   length_feet       180 non-null    int64
 4   model_year        180 non-null    int64
 5   vin               180 non-null    object
 6   acquisition_date  180 non-null    object
 7   status            180 non-null    object
 8   current_location  180 non-null    object
dtypes: int64(3), object(6)
memory usage: 12.8+ KB

In [391]:
df_trailers.head(3)

,trailer_id,trailer_number,trailer_type,length_feet,model_year,vin,acquisition_date,status,current_location
0,TRL00001,4290,Refrigerated,53,2016,1AV889081755621178,2018-05-11,Active,Kansas City
1,TRL00002,8848,Dry Van,53,2018,1BU942062588832828,2018-11-24,Active,Kansas City
2,TRL00003,6147,Dry Van,53,2022,1AV669057807416326,2019-01-28,Active,Milwaukee

In [392]:
df_routes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   route_id                58 non-null     object
 1   origin_city             58 non-null     object
 2   origin_state            58 non-null     object
 3   destination_city        58 non-null     object
 4   destination_state       58 non-null     object
 5   typical_distance_miles  58 non-null     int64
 6   base_rate_per_mile      58 non-null     float64
 7   fuel_surcharge_rate     58 non-null     float64
 8   typical_transit_days    58 non-null     int64
dtypes: float64(2), int64(2), object(5)
memory usage: 4.2+ KB

In [393]:
df_routes.head(3)

,route_id,origin_city,origin_state,destination_city,destination_state,typical_distance_miles,base_rate_per_mile,fuel_surcharge_rate,typical_transit_days
0,RTE00001,Atlanta,GA,Chicago,IL,677,1.70,0.19,1
1,RTE00002,Atlanta,GA,Miami,FL,697,2.08,0.22,1
2,RTE00003,Chicago,IL,Los Angeles,CA,2003,2.55,0.29,3

In [394]:
df_loads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   load_id              85410 non-null  object
 1   customer_id          85410 non-null  object
 2   route_id             85410 non-null  object
 3   load_date            85410 non-null  object
 4   load_type            85410 non-null  object
 5   weight_lbs           85410 non-null  int64
 6   pieces               85410 non-null  int64
 7   revenue              85410 non-null  float64
 8   fuel_surcharge       85410 non-null  float64
 9   accessorial_charges  85410 non-null  int64
 10  load_status          85410 non-null  object
 11  booking_type         85410 non-null  object
dtypes: float64(2), int64(3), object(7)
memory usage: 7.8+ MB

In [395]:
df_loads.head(3)

,load_id,customer_id,route_id,load_date,load_type,weight_lbs,pieces,revenue,fuel_surcharge,accessorial_charges,load_status,booking_type
0,LOAD00000001,CUST00183,RTE00019,2022-01-01,Dry Van,19178,13,3045.23,406.72,100,Completed,Spot
1,LOAD00000002,CUST00076,RTE00058,2022-01-01,Dry Van,27761,22,1224.48,98.61,0,Completed,Dedicated
2,LOAD00000003,CUST00027,RTE00048,2022-01-01,Refrigerated,35594,16,7171.12,792.88,0,Completed,Spot

In [396]:
df_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   trip_id                85410 non-null  object
 1   load_id                85410 non-null  object
 2   driver_id              83696 non-null  object
 3   truck_id               83738 non-null  object
 4   trailer_id             83730 non-null  object
 5   dispatch_date          85410 non-null  object
 6   actual_distance_miles  85410 non-null  int64
 7   actual_duration_hours  85410 non-null  float64
 8   fuel_gallons_used      85410 non-null  float64
 9   average_mpg            85410 non-null  float64
 10  idle_time_hours        85410 non-null  float64
 11  trip_status            85410 non-null  object
dtypes: float64(4), int64(1), object(7)
memory usage: 7.8+ MB

In [397]:
df_trips.head(3)

,trip_id,load_id,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,trip_status
0,TRIP00000001,LOAD00000001,DRV00117,TRK00035,TRL00167,2022-01-01,1314,26.2,183.8,7.15,3.5,Completed
1,TRIP00000002,LOAD00000002,DRV00141,TRK00108,TRL00082,2022-01-01,515,8.6,93.6,5.50,8.3,Completed
2,TRIP00000003,LOAD00000003,DRV00032,TRK00031,TRL00138,2022-01-01,2509,45.0,339.1,7.40,12.0,Completed

In [398]:
df_fuel_purchases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196442 entries, 0 to 196441
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   fuel_purchase_id  196442 non-null  object
 1   trip_id           196442 non-null  object
 2   truck_id          192562 non-null  object
 3   driver_id         192454 non-null  object
 4   purchase_date     196442 non-null  object
 5   location_city     196442 non-null  object
 6   location_state    196442 non-null  object
 7   gallons           196442 non-null  float64
 8   price_per_gallon  196442 non-null  float64
 9   total_cost        196442 non-null  float64
 10  fuel_card_number  196442 non-null  object
dtypes: float64(3), object(8)
memory usage: 16.5+ MB

In [399]:
df_fuel_purchases.head(3)

,fuel_purchase_id,trip_id,truck_id,driver_id,purchase_date,location_city,location_state,gallons,price_per_gallon,total_cost,fuel_card_number
0,FUEL00000001,TRIP00051284,TRK00045,DRV00102,2023-10-22 05:00:00,Columbus,MN,131.6,3.399,447.31,FC567161
1,FUEL00000002,TRIP00073723,TRK00013,NaN,2024-08-04 08:00:00,New York,AZ,139.9,3.180,444.88,FC717910
2,FUEL00000003,TRIP00018286,TRK00024,DRV00142,2022-08-23 13:00:00,Seattle,NE,189.3,3.804,720.10,FC912816

In [400]:
df_maintenance_records.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2920 entries, 0 to 2919
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   maintenance_id       2920 non-null   object
 1   truck_id             2920 non-null   object
 2   maintenance_date     2920 non-null   object
 3   maintenance_type     2920 non-null   object
 4   odometer_reading     2920 non-null   int64
 5   labor_hours          2920 non-null   float64
 6   labor_cost           2920 non-null   float64
 7   parts_cost           2920 non-null   float64
 8   total_cost           2920 non-null   float64
 9   facility_location    2920 non-null   object
 10  downtime_hours       2920 non-null   float64
 11  service_description  2920 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 273.9+ KB

In [401]:
df_maintenance_records.head(3)

,maintenance_id,truck_id,maintenance_date,maintenance_type,odometer_reading,labor_hours,labor_cost,parts_cost,total_cost,facility_location,downtime_hours,service_description
0,MAINT00000001,TRK00085,2022-01-01,Inspection,400255,7.8,781.42,10.41,791.83,Kansas City,22.2,Emergency Inspection
1,MAINT00000002,TRK00041,2022-01-01,Tire,268041,0.9,80.91,3207.16,3288.07,Seattle,8.0,Scheduled Tire
2,MAINT00000003,TRK00090,2022-01-01,Preventive,698915,7.2,733.18,1570.57,2303.75,Miami,16.5,Routine Preventive

In [402]:
df_delivery_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170820 entries, 0 to 170819
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   event_id            170820 non-null  object
 1   load_id             170820 non-null  object
 2   trip_id             170820 non-null  object
 3   event_type          170820 non-null  object
 4   facility_id         170820 non-null  object
 5   scheduled_datetime  170820 non-null  object
 6   actual_datetime     170820 non-null  object
 7   detention_minutes   170820 non-null  int64
 8   on_time_flag        170820 non-null  bool
 9   location_city       170820 non-null  object
 10  location_state      170820 non-null  object
dtypes: bool(1), int64(1), object(9)
memory usage: 13.2+ MB

In [403]:
df_delivery_events.head(3)

,event_id,load_id,trip_id,event_type,facility_id,scheduled_datetime,actual_datetime,detention_minutes,on_time_flag,location_city,location_state
0,EVT00000001,LOAD00000001,TRIP00000001,Pickup,FAC00034,2022-01-01 18:00:00.000000,2022-01-01 20:58:55.918185,0,False,Houston,TX
1,EVT00000002,LOAD00000001,TRIP00000001,Delivery,FAC00046,2022-01-02 23:10:55.918185,2022-01-02 21:30:22.142060,230,True,Detroit,MI
2,EVT00000003,LOAD00000002,TRIP00000002,Pickup,FAC00015,2022-01-01 18:00:00.000000,2022-01-01 17:37:26.608430,62,True,Kansas City,MO

In [404]:
df_driver_monthly_metrics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4464 entries, 0 to 4463
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   driver_id              4464 non-null   object
 1   month                  4464 non-null   object
 2   trips_completed        4464 non-null   int64
 3   total_miles            4464 non-null   int64
 4   total_revenue          4464 non-null   float64
 5   average_mpg            4464 non-null   float64
 6   total_fuel_gallons     4464 non-null   float64
 7   on_time_delivery_rate  4464 non-null   float64
 8   average_idle_hours     4464 non-null   float64
dtypes: float64(5), int64(2), object(2)
memory usage: 314.0+ KB

In [405]:
df_driver_monthly_metrics.head(3)

,driver_id,month,trips_completed,total_miles,total_revenue,average_mpg,total_fuel_gallons,on_time_delivery_rate,average_idle_hours
0,DRV00001,2022-01-01,26,36620,79141.59,6.61,5574.7,0.385,8.2
1,DRV00001,2022-02-01,9,13515,27133.87,6.69,2095.1,0.333,6.8
2,DRV00001,2022-03-01,20,30361,62399.62,6.36,4792.2,0.550,7.5

### Formateo de datos

#### Creación de funciones para formatear datos

In [406]:
def convert_to_lowercase(df):
    """
    Convierte a minúsculas todas las columnas de texto
    de un DataFrame.
    """
    df = df.copy()

    text_cols = df.select_dtypes(include=["object", "string"]).columns

    for col in text_cols:
        df[col] = df[col].str.lower()

    return df

In [407]:
def convert_dates(df, date_columns):
    """
    Convierte columnas de fecha a tipo datetime.
    """
    df = df.copy()

    for col in date_columns:
        df[col] = pd.to_datetime(df[col])

    return df

In [408]:
def convert_float(df, int_columns):
    """
    Convierte columnas de tipo int a tipo float con 2 decimales (para revenues, currencies).
    """
    df = df.copy()

    for col in int_columns:
        df[col] = df[col].astype('float').round(2)

    return df

#### Aplicación de funciones y cambios

In [409]:
# Establecer todos los datasets en minúsculas
df_customers = convert_to_lowercase(df_customers)
df_drivers = convert_to_lowercase(df_drivers)
df_trucks = convert_to_lowercase(df_trucks)
df_trailers = convert_to_lowercase(df_trailers)
df_routes = convert_to_lowercase(df_routes)
df_loads = convert_to_lowercase(df_loads)
df_trips = convert_to_lowercase(df_trips)
df_fuel_purchases = convert_to_lowercase(df_fuel_purchases)
df_maintenance_records = convert_to_lowercase(df_maintenance_records)
df_delivery_events = convert_to_lowercase(df_delivery_events)

In [410]:
# Establecer las fechas en todos los datasets
df_customers = convert_dates(df_customers, ['contract_start_date'])
df_drivers = convert_dates(df_drivers, ['hire_date', 'date_of_birth'])
df_trucks = convert_dates(df_trucks, ['acquisition_date'])
df_trailers = convert_dates(df_trailers, ['acquisition_date'])
df_loads = convert_dates(df_loads, ['load_date'])
df_trips = convert_dates(df_trips, ['dispatch_date'])
df_fuel_purchases = convert_dates(df_fuel_purchases, ['purchase_date'])
df_maintenance_records = convert_dates(
    df_maintenance_records, ['maintenance_date'])
df_delivery_events = convert_dates(df_delivery_events, [
                                   'scheduled_datetime', 'actual_datetime'])

In [411]:
# Cambiar tipo de dato 'object' por 'float64' para revenues
df_customers['annual_revenue_potential'] = df_customers['annual_revenue_potential'].astype(
    'float64').round(2)

In [412]:
# Cambiar boleano por numero binario
df_delivery_events["on_time_flag"] = df_delivery_events['on_time_flag'].astype(
    int)

### Revisar y tratar valores nulos

In [413]:
datasets = {
    "customers": df_customers,
    "drivers": df_drivers,
    "trucks": df_trucks,
    "trailers": df_trailers,
    "routes": df_routes,
    "loads": df_loads,
    "trips": df_trips,
    "fuel_purchases": df_fuel_purchases,
    "maintenance_records": df_maintenance_records,
    "delivery_events": df_delivery_events,
    "driver_monthly_metrics": df_driver_monthly_metrics
}

for name, df in datasets.items():
    print(f"\n{'='*20} {name.upper()} {'='*20}")
    print(df.isnull().sum())

==================== CUSTOMERS ====================
customer_id                 0
customer_name               0
customer_type               0
credit_terms_days           0
primary_freight_type        0
account_status              0
contract_start_date         0
annual_revenue_potential    0
dtype: int64

==================== DRIVERS ====================
driver_id              0
first_name             0
last_name              0
hire_date              0
termination_date     124
license_number         0
license_state          0
date_of_birth          0
home_terminal          0
employment_status      0
cdl_class              0
years_experience       0
dtype: int64

==================== TRUCKS ====================
truck_id                 0
unit_number              0
make                     0
model_year               0
vin                      0
acquisition_date         0
acquisition_mileage      0
fuel_type                0
tank_capacity_gallons    0
status                   0
home_terminal            0
dtype: int64

==================== TRAILERS ====================
trailer_id          0
trailer_number      0
trailer_type        0
length_feet         0
model_year          0
vin                 0
acquisition_date    0
status              0
current_location    0
dtype: int64

==================== ROUTES ====================
route_id                  0
origin_city               0
origin_state              0
destination_city          0
destination_state         0
typical_distance_miles    0
base_rate_per_mile        0
fuel_surcharge_rate       0
typical_transit_days      0
dtype: int64

==================== LOADS ====================
load_id                0
customer_id            0
route_id               0
load_date              0
load_type              0
weight_lbs             0
pieces                 0
revenue                0
fuel_surcharge         0
accessorial_charges    0
load_status            0
booking_type           0
dtype: int64

==================== TRIPS ====================
trip_id                     0
load_id                     0
driver_id                1714
truck_id                 1672
trailer_id               1680
dispatch_date               0
actual_distance_miles       0
actual_duration_hours       0
fuel_gallons_used           0
average_mpg                 0
idle_time_hours             0
trip_status                 0
dtype: int64

==================== FUEL_PURCHASES ====================
fuel_purchase_id       0
trip_id                0
truck_id            3880
driver_id           3988
purchase_date          0
location_city          0
location_state         0
gallons                0
price_per_gallon       0
total_cost             0
fuel_card_number       0
dtype: int64

==================== MAINTENANCE_RECORDS ====================
maintenance_id         0
truck_id               0
maintenance_date       0
maintenance_type       0
odometer_reading       0
labor_hours            0
labor_cost             0
parts_cost             0
total_cost             0
facility_location      0
downtime_hours         0
service_description    0
dtype: int64

==================== DELIVERY_EVENTS ====================
event_id              0
load_id               0
trip_id               0
event_type            0
facility_id           0
scheduled_datetime    0
actual_datetime       0
detention_minutes     0
on_time_flag          0
location_city         0
location_state        0
dtype: int64

==================== DRIVER_MONTHLY_METRICS ====================
driver_id                0
month                    0
trips_completed          0
total_miles              0
total_revenue            0
average_mpg              0
total_fuel_gallons       0
on_time_delivery_rate    0
average_idle_hours       0
dtype: int64

In [414]:
print("==================== VALORES_NULOS_DRIVERS ====================")
df_drivers[df_drivers.isnull().any(axis=1)].head(3)

==================== VALORES_NULOS_DRIVERS ====================

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,drv00001,jennifer,hernandez,2014-10-31,NaN,dl673510887,wa,1973-11-07,denver,active,a,3
1,drv00002,william,martin,2020-10-02,NaN,dl128955006,ga,1976-11-03,columbus,active,a,20
2,drv00003,charles,hernandez,2021-09-21,NaN,dl523076025,nc,1970-04-06,salt lake city,active,a,19

In [415]:
print("==================== VALORES_NULOS_TRIPS ====================")
df_trips[df_trips.isnull().any(axis=1)].head(3)

==================== VALORES_NULOS_TRIPS ====================

,trip_id,load_id,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,trip_status
66,trip00000067,load00000067,NaN,trk00112,trl00040,2022-01-01,2433,40.0,427.6,5.69,9.2,completed
69,trip00000070,load00000070,drv00077,NaN,trl00040,2022-01-01,711,14.2,105.5,6.74,9.7,completed
73,trip00000074,load00000074,drv00051,NaN,trl00141,2022-01-02,2937,51.6,428.8,6.85,9.7,completed

In [416]:
print("==================== VALORES_NULOS_FUEL_PURCHASES ====================")
df_fuel_purchases[df_fuel_purchases.isnull().any(axis=1)].head(3)

==================== VALORES_NULOS_FUEL_PURCHASES ====================

,fuel_purchase_id,trip_id,truck_id,driver_id,purchase_date,location_city,location_state,gallons,price_per_gallon,total_cost,fuel_card_number
1,fuel00000002,trip00073723,trk00013,NaN,2024-08-04 08:00:00,new york,az,139.9,3.180,444.88,fc717910
4,fuel00000005,trip00069700,trk00054,NaN,2024-06-13 09:00:00,columbus,az,185.3,3.422,634.10,fc391024
11,fuel00000012,trip00079405,NaN,drv00085,2024-10-16 19:00:00,los angeles,wi,75.4,3.988,300.70,fc535781

Conclusión: No hay necesidad de cambiar los valores nulos existentes.

### Revisar y tratar los valores duplicados

In [417]:
datasets = {
    "customers": df_customers,
    "drivers": df_drivers,
    "trucks": df_trucks,
    "trailers": df_trailers,
    "routes": df_routes,
    "loads": df_loads,
    "trips": df_trips,
    "fuel_purchases": df_fuel_purchases,
    "maintenance_records": df_maintenance_records,
    "delivery_events": df_delivery_events,
    "driver_monthly_metrics": df_driver_monthly_metrics
}

for name, df in datasets.items():
    print(f"\n{'='*20} {name.upper()} {'='*20}")
    print(df.duplicated().sum())

==================== CUSTOMERS ====================
0

==================== DRIVERS ====================
0

==================== TRUCKS ====================
0

==================== TRAILERS ====================
0

==================== ROUTES ====================
0

==================== LOADS ====================
0

==================== TRIPS ====================
0

==================== FUEL_PURCHASES ====================
0

==================== MAINTENANCE_RECORDS ====================
0

==================== DELIVERY_EVENTS ====================
0

==================== DRIVER_MONTHLY_METRICS ====================
0

### Enriquecimiento y limpieza final

#### Eliminación de columnas innecesarias para el proyecto

In [418]:
df_drivers = df_drivers.drop(
    ['license_number', 'license_state', 'cdl_class'], axis=1)
df_trucks = df_trucks.drop([
    'vin', 'acquisition_date', 'acquisition_mileage'], axis=1)
df_trailers = df_trailers.drop(
    ['vin', 'acquisition_date', 'current_location'], axis=1)
df_loads = df_loads.drop(['load_status'], axis=1)
df_trips = df_trips.drop(['trip_status'], axis=1)
df_fuel_purchases = df_fuel_purchases.drop(['truck_id', 'driver_id'], axis=1)

### Exportamos tablas limpias

In [420]:
df_customers.to_csv('Dataset limpios/customers_clean.csv', index=False)
df_drivers.to_csv('Dataset limpios/drivers_clean.csv', index=False)
df_trucks.to_csv('Dataset limpios/trucks_clean.csv', index=False)
df_trailers.to_csv('Dataset limpios/trailers_clean.csv', index=False)
df_routes.to_csv('Dataset limpios/routes_clean.csv', index=False)
df_loads.to_csv('Dataset limpios/loads_clean.csv', index=False)
df_trips.to_csv('Dataset limpios/trips_clean.csv', index=False)
df_fuel_purchases.to_csv(
    'Dataset limpios/fuel_purchases_clean.csv', index=False)
df_maintenance_records.to_csv(
    'Dataset limpios/maintenance_records_clean.csv', index=False)
df_delivery_events.to_csv(
    'Dataset limpios/delivery_events_clean.csv', index=False)
df_driver_monthly_metrics.to_csv(
    'Dataset limpios/driver_monthly_metrics_clean.csv', index=False)